### ISSUE TITLE
Validation against multiple Trust Anchors

### ISSUE THREAD

**Issue by SchulzeStTSI** [WorldHealthOrganization/ddcc-gateway-lib#3]
The dgc lib should be able to download from the GW trustlist the trustanchor list by using /trustlist/trustanchor. After validating the trustanchors with the origin gateway trust anchor, all items from the federated trustlist must be accepted which are signed by any of this anchors.

**Comment by f11h** [comment]
Will be implemented here: https://github.com/eu-digital-green-certificates/dgc-lib/pull/87

**Comment by f11h** [comment]
Implemented and merged with Version 1.1.12
